language: rust
cache: cargo
rust:
  - nightly
matrix:
  allow-failures:
  - rust: nightly
  fast_finish: true

env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$HOME/.cargo/bin:$PATH"
- rustup component add rustfmt
- rustup component add clippy-preview

script:
  - cargo fmt --all -- --check `find src -iname "*.rs"`
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy -- -D clippy::all
